require('dotenv').config();
const express = require('express'); const cors = require('cors'); const helmet = require('helmet'); const morgan = require('morgan'); const rateLimit = require('express-rate-limit'); const http = require('http'); const { Server } = require('socket.io');
const { errorHandler } = require('./src/middleware/errorHandler'); const { query } = require('./src/config/database');
const authRoutes = require('./src/routes/authRoutes'); const carRoutes = require('./src/routes/carRoutes'); const reservationRoutes = require('./src/routes/reservationRoutes'); const paymentRoutes = require('./src/routes/paymentRoutes'); const showroomSubscriptionPaymentRoutes = require('./src/routes/showroomSubscriptionPaymentRoutes'); const reviewRoutes = require('./src/routes/reviewRoutes'); const complaintRoutes = require('./src/routes/complaintRoutes'); const notificationRoutes = require('./src/routes/notificationRoutes'); const handoverRoutes = require('./src/routes/handoverRoutes'); const adminRoutes = require('./src/routes/adminRoutes'); const adminShowroomSubscriptionRoutes = require('./src/routes/adminShowroomSubscriptionRoutes'); const employeeRoutes = require('./src/routes/employeeRoutes'); const employeeSelfRoutes = require('./src/routes/employeeSelfRoutes'); const { initCronJobs } = require('./src/utils/cronJobs'); const advertisementRoutes = require('./src/routes/advertisementRoutes'); const whatsappRoutes = require('./src/routes/whatsappRoutes'); const financeRoutes = require('./src/routes/financeRoutes'); const supplierFinanceRoutes = require('./src/routes/supplierFinanceRoutes'); const supplierShowroomRoutes = require('./src/routes/supplierShowroomRoutes'); const supplierContextRoutes = require('./src/routes/supplierContextRoutes');
const app=express(); app.set('trust proxy',1); const server=http.createServer(app); const testEmailRoutes=require('./src/routes/testEmailRoutes');
const io=new Server(server,{cors:{origin:['http://localhost:3000','http://localhost:5173',process.env.FRONTEND_URL].filter(Boolean),methods:['GET','POST']}}); app.set('io',io); io.on('connection',(socket)=>{socket.on('join_room',(userId)=>socket.join(`user_${userId}`));socket.on('join_complaint_room',(id)=>socket.join(`complaint_${id}`));});
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:['http://localhost:3000','http://localhost:5173',process.env.FRONTEND_URL].filter(Boolean),credentials:true})); app.use('/api/',rateLimit({windowMs:15*60*1000,max:process.env.NODE_ENV==='development'?10000:100})); app.use(express.json({limit:'10mb'})); app.use(express.urlencoded({extended:true,limit:'10mb'})); if(process.env.NODE_ENV==='development')app.use(morgan('dev'));
app.use('/api/auth',testEmailRoutes); app.use('/uploads',express.static('uploads')); app.use('/api/auth',authRoutes);
// When a supplier adds a car, force the location to one of that supplier's own active showrooms.
app.use('/api/cars', async (req,res,next)=>{ if(req.method!=='POST'||!req.user||req.user.role!=='supplier') return next(); try{const locationId=req.body?.location_id;if(!locationId)return res.status(400).json({success:false,message:'اختر المعرض الحالي قبل إضافة السيارة'});const r=await query(`SELECT id FROM locations WHERE id=$1 AND supplier_id=$2 AND COALESCE(is_active,TRUE)=TRUE AND subscription_status='active'`,[locationId,req.user.id]);if(!r.rows.length)return res.status(403).json({success:false,message:'لا يمكنك إضافة سيارة إلى معرض لا تملكه أو اشتراكه غير نشط'});next()}catch(e){next(e)}});
app.use('/api/cars',carRoutes); app.use('/api/supplier/showrooms',supplierShowroomRoutes); app.use('/api/supplier/context',supplierContextRoutes); app.use('/api/payments/showroom-subscription',showroomSubscriptionPaymentRoutes); app.use('/api/employee-self',employeeSelfRoutes); app.use('/api/employee',employeeRoutes); app.use('/api/reservations',reservationRoutes); app.use('/api/payments',paymentRoutes); app.use('/api/reviews',reviewRoutes); app.use('/api/complaints',complaintRoutes); app.use('/api/notifications',notificationRoutes); app.use('/api/whatsapp',whatsappRoutes); app.use('/api/finance',financeRoutes); app.use('/api/supplier-finance',supplierFinanceRoutes); app.use('/api/handover',handoverRoutes); app.use('/api/admin',adminRoutes); app.use('/api/admin/showroom-subscriptions',adminShowroomSubscriptionRoutes); app.use('/api/employees',employeeRoutes); app.use('/api/advertisementController',advertisementRoutes);
app.get('/api/health',(req,res)=>res.json({success:true,message:'🚗 Car Rental API is running!',timestamp:new Date().toISOString(),environment:process.env.NODE_ENV})); app.use('*',(req,res)=>res.status(404).json({success:false,message:`Route ${req.originalUrl} not found`})); app.use(errorHandler);
const PORT=process.env.PORT||5000; server.listen(PORT,()=>{console.log(`Car Rental API Server Port: ${PORT}`);initCronJobs(io)}); module.exports={app,server};
