import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { Building2, Save } from 'lucide-react';
import { adminAPI } from '../../services/api';

export default function ShowroomSubscriptionSettings() {
  const [form,setForm]=useState({monthly_price:'',annual_price:'',currency:'YER',enabled:true});
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  useEffect(()=>{adminAPI.getShowroomSubscriptionSettings().then(r=>setForm(r.data.data)).catch(e=>toast.error(e.response?.data?.message||'تعذر تحميل الإعدادات')).finally(()=>setLoading(false))},[]);
  const save=async(e)=>{e.preventDefault();setSaving(true);try{const r=await adminAPI.updateShowroomSubscriptionSettings(form);setForm(r.data.data);toast.success('تم حفظ أسعار اشتراكات المعارض')}catch(e){toast.error(e.response?.data?.message||'تعذر حفظ الإعدادات')}finally{setSaving(false)}};
  if(loading)return <div dir="rtl" style={{padding:40}}>جاري التحميل...</div>;
  return <main dir="rtl" style={{minHeight:'100vh',background:'#f5f8fa',padding:'34px',fontFamily:'inherit'}}><div style={{maxWidth:760,margin:'0 auto'}}><div style={{background:'#fff',borderRadius:20,padding:28,border:'1px solid #e5ecef',boxShadow:'0 8px 28px rgba(23,58,82,.06)'}}><div style={{display:'flex',alignItems:'center',gap:12,marginBottom:25}}><div style={{width:48,height:48,borderRadius:14,background:'#edf7f5',color:'#178263',display:'grid',placeItems:'center'}}><Building2/></div><div><div style={{color:'#178263',fontSize:12,fontWeight:900}}>إدارة المعارض</div><h1 style={{margin:'4px 0',fontSize:26,color:'#173a52'}}>اشتراكات المعارض</h1><p style={{margin:0,color:'#70818a'}}>الأدمن هو من يحدد الأسعار التي تظهر للموردين.</p></div></div><form onSubmit={save} style={{display:'grid',gap:18}}><label style={{fontWeight:800}}>السعر الشهري<input type="number" min="0" step="0.01" value={form.monthly_price} onChange={e=>setForm({...form,monthly_price:e.target.value})} style={input}/></label><label style={{fontWeight:800}}>السعر السنوي<input type="number" min="0" step="0.01" value={form.annual_price} onChange={e=>setForm({...form,annual_price:e.target.value})} style={input}/></label><label style={{fontWeight:800}}>العملة<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})} maxLength={10} style={input}/></label><label style={{display:'flex',alignItems:'center',gap:10,fontWeight:800}}><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> السماح للموردين بإضافة معارض جديدة</label><button disabled={saving} style={{border:0,borderRadius:12,padding:13,background:'#178263',color:'#fff',fontWeight:900,display:'flex',justifyContent:'center',alignItems:'center',gap:8}}><Save size={18}/>{saving?'جاري الحفظ...':'حفظ التغييرات'}</button></form></div></div></main>;
}
const input={display:'block',width:'100%',boxSizing:'border-box',marginTop:7,padding:12,border:'1px solid #d9e3e6',borderRadius:11,font:'inherit'};
